"""Methodology layer.

Data model, DSL + compiler, contract artifacts, mechanical evaluator, plugin
Protocol definitions. Per DEC-029, ``smai-core`` is the methodology layer:
runtime deps stay on the allowlist (``pydantic``, ``jsonschema``, stdlib);
imports of pipeline packages are mechanically forbidden by
``tools/check_deps.py``.
"""

from smai_core.dsl import (
    DslDocument,
    DslDocumentAdapter,
    ExperimentDocument,
    FactorModelDocument,
    load_dsl_document_from_json,
)
from smai_core.entities import (
    AggregationRule,
    AtomicMetricEntry,
    AtomicMetricRef,
    ComparisonRule,
    ControlledConditions,
    Entry,
    ExperimentDefinition,
    Factor,
    FactorModel,
    FidelityAnchor,
    FidelityAnchorAdapter,
    Level,
    MetricRef,
    MetricRefAdapter,
    MetricRegistry,
    NumericValue,
    PaperFidelityAnchor,
    ParametricFamily,
    ParametricMetricRef,
    ProposalFidelityAnchor,
    Registries,
    ReviewerAttestedFidelityAnchor,
    TechniqueParams,
    TechniqueParamValue,
    TechniqueRef,
    TrendCheck,
    ValidationCriteria,
    ValidationError,
    VerifiedExperimentDefinition,
)
from smai_core.factor_types import (
    AdditivePlugin,
    FactorTypePlugin,
    FactorTypePluginError,
    SubstitutivePlugin,
    load_builtin_factor_type_plugins,
)

__all__ = [
    "AdditivePlugin",
    "AggregationRule",
    "AtomicMetricEntry",
    "AtomicMetricRef",
    "ComparisonRule",
    "ControlledConditions",
    "DslDocument",
    "DslDocumentAdapter",
    "Entry",
    "ExperimentDefinition",
    "ExperimentDocument",
    "Factor",
    "FactorModel",
    "FactorModelDocument",
    "FactorTypePlugin",
    "FactorTypePluginError",
    "FidelityAnchor",
    "FidelityAnchorAdapter",
    "Level",
    "MetricRef",
    "MetricRefAdapter",
    "MetricRegistry",
    "NumericValue",
    "PaperFidelityAnchor",
    "ParametricFamily",
    "ParametricMetricRef",
    "ProposalFidelityAnchor",
    "Registries",
    "ReviewerAttestedFidelityAnchor",
    "SubstitutivePlugin",
    "TechniqueParamValue",
    "TechniqueParams",
    "TechniqueRef",
    "TrendCheck",
    "ValidationCriteria",
    "ValidationError",
    "VerifiedExperimentDefinition",
    "load_builtin_factor_type_plugins",
    "load_dsl_document_from_json",
]
