"""Methodology layer.

Data model, DSL + compiler, contract artifacts, mechanical evaluator, plugin
Protocol definitions. Per DEC-029, ``smai-core`` is the methodology layer:
runtime deps stay on the allowlist (``pydantic``, ``jsonschema``, stdlib);
imports of pipeline packages are mechanically forbidden by
``tools/check_deps.py``.
"""

from smai_core._compile import compile_experiment
from smai_core._runtime_keys import metric_ref_to_runtime_key
from smai_core.artifacts import (
    ARTIFACT_SCHEMA_VERSION,
    COMPILER_VERSION,
    ArtifactEnvelope,
    ArtifactKind,
    ContractArtifactSet,
    ExperimentPlan,
    ExperimentPlanBody,
    FixedVariable,
    HarnessContract,
    HarnessContractBody,
    SurfaceKind,
    TechniqueContract,
    TechniqueContractBody,
    ValidationConfig,
    ValidationConfigBody,
    artifact_hash,
    canonical_json,
    emit_artifacts,
    emit_factor_model_artifacts,
    freeze_with_hash,
)
from smai_core.data import load_metric_registry
from smai_core.defaults import load_default_registries
from smai_core.dsl import (
    DslDocument,
    DslDocumentAdapter,
    ExperimentDocument,
    FactorModelDocument,
    load_dsl_document_from_json,
)
from smai_core.entities import (
    AggregationRule,
    AtomicMetricEntry,
    AtomicMetricRef,
    ComparisonRule,
    ControlledConditions,
    Entry,
    ExperimentDefinition,
    Factor,
    FactorModel,
    FidelityAnchor,
    FidelityAnchorAdapter,
    Level,
    MetricRef,
    MetricRefAdapter,
    MetricRefNotRegistered,
    MetricRegistry,
    MetricRegistryEntry,
    NumericValue,
    PaperFidelityAnchor,
    ParametricFamily,
    ParametricMetricRef,
    ProposalFidelityAnchor,
    Registries,
    ReviewerAttestedFidelityAnchor,
    RuleSeverity,
    TechniqueParams,
    TechniqueParamValue,
    TechniqueRef,
    TrendCheck,
    ValidationCriteria,
    ValidationError,
    ValidationReport,
    VerificationFinding,
    VerifiedExperimentDefinition,
)
from smai_core.evaluation import (
    AGGREGATION_RULE_REGISTRY,
    COMPARISON_RULE_REGISTRY,
    AggregationFunction,
    AggregationRuleNotRegistered,
    ComparisonFunction,
    ComparisonRuleNotRegistered,
    get_aggregation_rule,
    get_comparison_rule,
)
from smai_core.factor_types import (
    AdditivePlugin,
    FactorTypePlugin,
    FactorTypePluginError,
    SubstitutivePlugin,
    load_builtin_factor_type_plugins,
)
from smai_core.verification import (
    TECHNIQUE_CATEGORY_V1_CLOSED_SET,
    VerificationError,
    verify,
    verify_experiment,
    verify_to_report,
)

__all__ = [
    "AGGREGATION_RULE_REGISTRY",
    "ARTIFACT_SCHEMA_VERSION",
    "AdditivePlugin",
    "AggregationFunction",
    "AggregationRule",
    "AggregationRuleNotRegistered",
    "ArtifactEnvelope",
    "ArtifactKind",
    "AtomicMetricEntry",
    "AtomicMetricRef",
    "COMPARISON_RULE_REGISTRY",
    "COMPILER_VERSION",
    "ComparisonFunction",
    "ComparisonRule",
    "ComparisonRuleNotRegistered",
    "ContractArtifactSet",
    "ControlledConditions",
    "DslDocument",
    "DslDocumentAdapter",
    "Entry",
    "ExperimentDefinition",
    "ExperimentDocument",
    "ExperimentPlan",
    "ExperimentPlanBody",
    "Factor",
    "FactorModel",
    "FactorModelDocument",
    "FactorTypePlugin",
    "FactorTypePluginError",
    "FidelityAnchor",
    "FidelityAnchorAdapter",
    "FixedVariable",
    "HarnessContract",
    "HarnessContractBody",
    "Level",
    "MetricRef",
    "MetricRefAdapter",
    "MetricRefNotRegistered",
    "MetricRegistry",
    "MetricRegistryEntry",
    "NumericValue",
    "PaperFidelityAnchor",
    "ParametricFamily",
    "ParametricMetricRef",
    "ProposalFidelityAnchor",
    "Registries",
    "ReviewerAttestedFidelityAnchor",
    "RuleSeverity",
    "SubstitutivePlugin",
    "SurfaceKind",
    "TECHNIQUE_CATEGORY_V1_CLOSED_SET",
    "TechniqueContract",
    "TechniqueContractBody",
    "TechniqueParamValue",
    "TechniqueParams",
    "TechniqueRef",
    "TrendCheck",
    "ValidationConfig",
    "ValidationConfigBody",
    "ValidationCriteria",
    "ValidationError",
    "ValidationReport",
    "VerificationError",
    "VerificationFinding",
    "VerifiedExperimentDefinition",
    "artifact_hash",
    "canonical_json",
    "compile_experiment",
    "emit_artifacts",
    "emit_factor_model_artifacts",
    "freeze_with_hash",
    "get_aggregation_rule",
    "get_comparison_rule",
    "load_builtin_factor_type_plugins",
    "load_default_registries",
    "load_dsl_document_from_json",
    "load_metric_registry",
    "metric_ref_to_runtime_key",
    "verify",
    "verify_experiment",
    "verify_to_report",
]
