"""Engine, pipeline-spec format, worker loop, checkpointer; SMAI PipelineSpec instances.

Public surface:

* Pipeline-tracking record types (Task 1.10): runtime instances of the
  methodology entities in ``smai_core.entities``, persisted via the
  ``MetadataStore`` plugin and driven through the orchestrator's state
  machines per ``designs/smai/01-data-model.md`` §5.
* Runtime configuration umbrella (Task 2.C3): :class:`PipelineSpec`,
  :class:`RuntimeConfig`, :class:`PluginSelection`,
  :func:`instantiate_plugins`, and the spec registry — see
  :mod:`smai_orchestrator.runtime`.
"""

from smai_orchestrator.entities import (
    CGState,
    ComparisonGroupRecord,
    EntryRecord,
    EntryState,
    FactorModelRecord,
    PaperRecord,
    PaperState,
    ProposalRecord,
    ProposalState,
    RunRecord,
    RunState,
)
from smai_orchestrator.runtime import (
    DEFAULT_TASK_ROLES,
    DuplicateSpecError,
    InstantiatedPlugins,
    PipelineSpec,
    PluginConformanceError,
    PluginInstantiationError,
    PluginNotFound,
    PluginOverrides,
    PluginSelection,
    RuntimeConfig,
    SpecNotRegisteredError,
    get_pipeline_spec,
    instantiate_plugins,
    list_discovered_plugins,
    list_registered_specs,
    register_pipeline_spec,
    reset_registry,
)
from smai_orchestrator.specs import (
    CG_ENTRIES_SPEC_NAME,
    CG_EXECUTION_SPEC_NAME,
    PAPER_INGESTION_SPEC_NAME,
    PROPOSAL_PIPELINE_SPEC_NAME,
    RUN_RECORD_SPEC_NAME,
    ArxivLatexFetcher,
    FetchedPaper,
    PaperFetcher,
    PaperFetchError,
    build_cg_entries_spec,
    build_cg_execution_spec,
    build_paper_ingestion_spec,
    build_proposal_pipeline_spec,
    build_run_record_spec,
    register_paper_ingestion_pipeline,
    register_proposal_pipeline,
    register_run_record_spec,
    register_smai_specs,
)

__all__ = [
    "CGState",
    "CG_ENTRIES_SPEC_NAME",
    "CG_EXECUTION_SPEC_NAME",
    "ComparisonGroupRecord",
    "DEFAULT_TASK_ROLES",
    "DuplicateSpecError",
    "EntryRecord",
    "EntryState",
    "FactorModelRecord",
    "InstantiatedPlugins",
    "PaperRecord",
    "PaperState",
    "PipelineSpec",
    "ArxivLatexFetcher",
    "FetchedPaper",
    "PAPER_INGESTION_SPEC_NAME",
    "PaperFetchError",
    "PaperFetcher",
    "PluginConformanceError",
    "PluginInstantiationError",
    "PluginNotFound",
    "PluginOverrides",
    "PluginSelection",
    "PROPOSAL_PIPELINE_SPEC_NAME",
    "ProposalRecord",
    "ProposalState",
    "RUN_RECORD_SPEC_NAME",
    "RunRecord",
    "RunState",
    "RuntimeConfig",
    "SpecNotRegisteredError",
    "build_cg_entries_spec",
    "build_cg_execution_spec",
    "build_paper_ingestion_spec",
    "build_proposal_pipeline_spec",
    "build_run_record_spec",
    "get_pipeline_spec",
    "instantiate_plugins",
    "list_discovered_plugins",
    "list_registered_specs",
    "register_paper_ingestion_pipeline",
    "register_pipeline_spec",
    "register_proposal_pipeline",
    "register_run_record_spec",
    "register_smai_specs",
    "reset_registry",
]
