"""Workspace shape and materialization.

Per ``10-runtime-and-templates.md`` §2. The runtime is shipped into a
workspace directory the agents have written into. The layout is fixed by
the runtime's expectations:

::

    workspace/
    ├── experiment.py                       # FIXED TEMPLATE
    ├── harness/                            # GENERATED by harness builder
    │   └── ...
    ├── techniques/
    │   ├── __init__.py                     # FIXED TEMPLATE
    │   ├── baseline.py                     # GENERATED by harness builder
    │   └── <technique_name>.py             # GENERATED by technique implementer
    ├── contracts/                          # IMMUTABLE — runtime drops these
    │   ├── harness_contract.json
    │   ├── technique_contract.json
    │   └── harness_api_manifest.json
    ├── validation_results.json             # written during validation runs
    └── metrics.json                        # written during full runs

The runtime drops ``contracts/`` in *after* the agents finish — those files
are the runtime's input mailbox, not an agent surface.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from smai_core import HarnessContract, TechniqueContract

from smai_runtime.manifest import HarnessAPIManifest
from smai_runtime.no_go_zone import (
    TEMPLATE_WORKSPACE_PATHS,
    read_template_bytes,
)

# Subdirectories the runtime expects to exist in a fully-assembled workspace.
WORKSPACE_SUBDIRS: tuple[str, ...] = ("harness", "techniques", "contracts")

# Names inside ``contracts/`` (§2 layout).
HARNESS_CONTRACT_FILENAME: str = "harness_contract.json"
TECHNIQUE_CONTRACT_FILENAME: str = "technique_contract.json"
HARNESS_API_MANIFEST_FILENAME: str = "harness_api_manifest.json"


def create_workspace_skeleton(workspace: Path) -> Path:
    """Make ``workspace`` and its standard subdirectories.

    Idempotent: existing dirs are left in place. Returns the absolute
    workspace path for caller convenience.
    """
    workspace.mkdir(parents=True, exist_ok=True)
    for sub in WORKSPACE_SUBDIRS:
        (workspace / sub).mkdir(parents=True, exist_ok=True)
    return workspace


def write_template_files(workspace: Path) -> list[Path]:
    """Drop the fixed-template files into ``workspace`` (§2 / §3).

    Templates are read byte-exactly from the runtime's resource directory
    so the on-disk hash will match :func:`compute_expected_hashes`. Parent
    directories (e.g., ``techniques/``) are created if missing.
    """
    written: list[Path] = []
    for rel in TEMPLATE_WORKSPACE_PATHS:
        target = workspace / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(read_template_bytes(rel))
        written.append(target)
    return written


def write_contracts(
    workspace: Path,
    *,
    harness_contract: HarnessContract,
    technique_contract: TechniqueContract,
    manifest: HarnessAPIManifest,
) -> dict[str, Path]:
    """Drop the three contract artifacts into ``workspace/contracts/`` (§2).

    Pydantic ``model_dump_json(indent=2)`` is human-readable; the runtime
    only needs valid JSON to round-trip the artifact, so any formatting is
    acceptable.
    """
    contracts_dir = workspace / "contracts"
    contracts_dir.mkdir(parents=True, exist_ok=True)

    harness_path = contracts_dir / HARNESS_CONTRACT_FILENAME
    technique_path = contracts_dir / TECHNIQUE_CONTRACT_FILENAME
    manifest_path = contracts_dir / HARNESS_API_MANIFEST_FILENAME

    harness_path.write_text(harness_contract.model_dump_json(indent=2))
    technique_path.write_text(technique_contract.model_dump_json(indent=2))
    manifest_path.write_text(manifest.model_dump_json(indent=2))

    return {
        HARNESS_CONTRACT_FILENAME: harness_path,
        TECHNIQUE_CONTRACT_FILENAME: technique_path,
        HARNESS_API_MANIFEST_FILENAME: manifest_path,
    }


def materialize_workspace(
    workspace: Path,
    *,
    harness_contract: HarnessContract,
    technique_contract: TechniqueContract,
    manifest: HarnessAPIManifest,
) -> Path:
    """End-to-end workspace assembly: skeleton + templates + contracts (§2).

    The harness ``harness/*.py`` and technique ``techniques/<name>.py`` files
    are NOT written here — those are agent products and arrive via separate
    ``ArtifactStore`` writes. This function is what the orchestrator calls
    to lay down the runtime-owned scaffolding before invoking
    ``experiment.py``.
    """
    create_workspace_skeleton(workspace)
    write_template_files(workspace)
    write_contracts(
        workspace,
        harness_contract=harness_contract,
        technique_contract=technique_contract,
        manifest=manifest,
    )
    return workspace


def load_contracts(
    workspace: Path,
) -> tuple[HarnessContract, TechniqueContract, HarnessAPIManifest]:
    """Round-trip the three contract artifacts from ``workspace/contracts/`` (§3.4).

    Used by the fixed ``experiment.py`` template at run start. Each artifact
    is parsed with its Pydantic model so the runtime fails closed on
    structurally invalid contract files.
    """
    contracts_dir = workspace / "contracts"
    harness_contract = HarnessContract.model_validate_json(
        (contracts_dir / HARNESS_CONTRACT_FILENAME).read_text()
    )
    technique_contract = TechniqueContract.model_validate_json(
        (contracts_dir / TECHNIQUE_CONTRACT_FILENAME).read_text()
    )
    manifest = HarnessAPIManifest.model_validate_json(
        (contracts_dir / HARNESS_API_MANIFEST_FILENAME).read_text()
    )
    return harness_contract, technique_contract, manifest


def build_runtime_config(
    *,
    harness_contract: HarnessContract,
    technique_contract: TechniqueContract,
    seed: int,
) -> dict[str, Any]:
    """Build the ``config`` dict passed to ``build_harness`` and ``apply`` (§3.4 / §8.3).

    Carries the seed, the technique's params and ``level_value``, and the
    flattened ``HarnessContract.fixed_variables``. JSONPath flattening uses
    a ``.``-separator scheme: ``optimization.learning_rate`` lands at
    ``config["optimization.learning_rate"]`` — the harness reads its
    fixed variables back out by the same JSONPath strings the contract
    declared.
    """
    config: dict[str, Any] = {
        "seed": seed,
        "params": dict(technique_contract.body.technique_params or {}),
        "level_value": (
            technique_contract.body.level_value.model_dump(mode="json")
            if technique_contract.body.level_value is not None
            else None
        ),
    }
    for fv in harness_contract.body.fixed_variables:
        config[fv.path] = fv.value
    return config


def write_validation_results(
    workspace: Path,
    payload: dict[str, Any],
) -> Path:
    """Write structured validation output during validation runs (§10.4)."""
    target = workspace / "validation_results.json"
    target.write_text(json.dumps(payload, sort_keys=True, indent=2))
    return target
